#!/bin/bash
 
xsetroot -cursor_name left_ptr
sxhkd &
 
bspc config border_width	2
bspc config window_gap		20
 
bspc config split_ratio		0.62
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod1
 
bspc config automatic_scheme	spiral
 
bspc rule -a Firefox desktop='^2'
bspc rule -a code desktop='^4' state=floating follow=on

bspc monitor -d 1 2 3 4 5 6
